module.exports.ERROR_TYPES = {
  'ACCESS_FORBIDDEN': 'ACCESS_FORBIDDEN',
  'DATA_MISSING': 'DATA_MISSING',
  'EMAIL_ALREADY_USED':'EMAIL_ALREADY_USED',
  'INCORRECT_PASSWORD':'INCORRECT_PASSWORD',
  'INVALID_DATA':'INVALID_DATA',
  'INVALID_TOKEN': 'INVALID_TOKEN',
  'MEMBER_ALREADY_ADDED': 'MEMBER_ALREADY_ADDED',
  'NOT_FOUND': 'NOT_FOUND',
  'USER_NOT_FOUND':'USER_NOT_FOUND',
  'USERNAME_TAKEN': 'USERNAME_TAKEN',
};
