module.exports.ERROR_TYPES = {
  'DATA_MISSING': 'DATA_MISSING',
  'EMAIL_ALREADY_USED':'EMAIL_ALREADY_USED',
  'INCORRECT_PASSWORD':'INCORRECT_PASSWORD',
  'INVALID_DATA':'INVALID_DATA',
  'INVALID_TOKEN': 'INVALID_TOKEN',
  'NOT_FOUND': 'NOT_FOUND',
  'USER_NOT_FOUND':'USER_NOT_FOUND',
  'USERNAME_TAKEN': 'USERNAME_TAKEN',
};
