module.exports.ERROR_TYPES = {
  'EMAIL_ALREADY_USED':'EMAIL_ALREADY_USED',
  'INCORRECT_PASSWORD':'INCORRECT_PASSWORD',
  'INVALID_DATA':'INVALID_DATA',
  'USER_NOT_FOUND':'USER_NOT_FOUND',
  'USERNAME_TAKEN': 'USERNAME_TAKEN',
};
